controllers/ApplicationController.php
<?php


namespace app\controllers;

use app\components\AlfaApi;
use app\components\ApplicationService;
use app\models\ApplicationForm;
use app\models\ApplicationSearch;
use DateTimeImmutable;
use GuzzleHttp\Exception\GuzzleException;
use Yii;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * Контроллер для работы с заявками
 */
class ApplicationController extends Controller
{
    /**
     * Отображение всех заявок + фильтрация по таблице с заявками
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new ApplicationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->get());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
        ]);
    }

    /**
     * Создание новой заявки
     *
     * @return string
     * @throws HttpException
     */
    public function actionNew()
    {
        $form = new ApplicationForm();
        if (!Yii::$app->request->isPost) {
            $title = 'Добавить заявку';

            return $this->render('newApplication', [
                'model' => $form,
                'title' => $title,
            ]);
        }

        $form->attributes = Yii::$app->request->post('ApplicationForm');

        if (!$form->validate()) {
            echo json_encode($form->getErrors());
            exit;
        }

        $applicationService = new ApplicationService(new AlfaApi());
        $app = $applicationService->getNewApplicationByForm($form);

        if (!$app->save()) {
            throw new HttpException(
                500,
                "Невозможно сохранить в базу заявку {$app->getId()}. Ошибка при сохранении в базу"
            );
        }

        $app->setAlfaId($applicationService->sendApplicationByForm($app));
        $app->setLastCheckStatusAt(new DateTimeImmutable());
        if (!$app->save()) {
            throw new HttpException(
                500,
                "Невозможно обновить last_check_status_at у заявки {$app->getId()}. Ошибка при сохранении в базу"
            );
        }

        echo 'Success validation';
    }

    /**
     * Проверка заявки на дубли
     *
     * @return array|false[]
     * @throws HttpException
     * @throws GuzzleException
     */
    public function actionAjaxCheckDouble()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if (Yii::$app->request->isPost) {
            $form = new ApplicationForm();
            $form->attributes = Yii::$app->request->post('ApplicationForm');
            if (!$form->validate()) {
                return ActiveForm::validate($form);
            }

            $applicationService = new ApplicationService(new AlfaApi());
            $hasDouble = $applicationService->hasDoubles(
                inn: $form->inn,
                productCodes: [$form->productCode],
                phoneNumbers: [$form->phoneNumber],
            );

            return [
                'hasDouble' => $hasDouble
            ];
        }

        throw new HttpException(405);
    }
}

views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header>
    <?php
    NavBar::begin([
        'brandLabel' => 'Заявки а Альфа Банк',
        'brandUrl' => Yii::$app->urlManager->createUrl('application/index'),
        'options' => [
            'class' => 'navbar navbar-expand-md navbar-dark bg-dark fixed-top',
        ],
        'innerContainerOptions' => [
            'class' => 'container-fluid',
        ]
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => [
            ['label' => 'Новая заявка', 'url' => ['/application/new']],
        ],
    ]);
    NavBar::end();
    ?>
</header>

<main role="main" class="flex-shrink-0">
    <div class="container-fluid">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer class="footer mt-auto py-3 text-muted">
    <div class="container-fluid">
        <p class="float-left">&copy; My Company <?= date('Y') ?></p>
        <p class="float-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>